### ISSUE TITLE
Is this code valid?

### ISSUE THREAD

**Issue by techsin** [fbeline/Design-Patterns-JS#22]
In observer pattern you have this code 

```

    unregister(observer) {
        this.actions.remove.filter(function(el) {
            return el !== observer;
        });
    }
```

this.actions refer to an array. Yet arrays dont have a function called remove?

**Comment by fbeline** [comment]
No, it was not :man_facepalming: 

https://github.com/fbeline/Design-Patterns-JS/pull/26
